#!/usr/bin/env python3
"""Hand-correct Genesis chapters 2-3 word by word."""
import json, sys

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

with open('K:/TorahByWord/genesis.json', 'r', encoding='utf-8') as f:
    d = json.load(f)

# Chapter 2 corrections: (verse_num, word_idx, correct_gloss)
CH2 = [
    (1, 3, 'and·the·earth'),
    (1, 4, 'and·all·their·host'),
    (2, 4, 'his·work'),
    (2, 7, 'and·rested'),
    (2, 10, 'from·all·his·work'),
    (3, 2, 'the·day'),
    (3, 4, 'and·sanctified'),
    (3, 5, 'it'),
    (3, 7, 'in·it'),
    (3, 8, 'rested'),
    (3, 9, 'from·all·his·work'),
    (3, 10, 'which·created'),
    (3, 12, 'to·do'),
    (4, 1, 'generations·of'),
    (4, 3, 'and·the·earth'),
    (4, 4, 'when·created'),
    (4, 6, 'making'),
    (4, 9, 'earth'),
    (4, 10, 'and·heaven'),
    (5, 1, 'shrub·of'),
    (5, 4, 'was'),
    (5, 6, 'and·every·plant·of'),
    (5, 12, 'had·rained'),
    (5, 17, 'there·was·no'),
    (5, 19, 'the·ground'),
    (6, 0, 'and·a·mist'),
    (6, 1, 'went·up'),
    (6, 2, 'from·the·earth'),
    (6, 3, 'and·watered'),
    (6, 4, 'all·the·face·of'),
    (6, 5, 'the·ground'),
    (7, 0, 'and·formed'),
    (7, 3, 'the·man'),
    (7, 4, 'dust'),
    (7, 5, 'from·the·ground'),
    (7, 6, 'and·breathed'),
    (7, 7, 'into·his·nostrils'),
    (7, 8, 'the·breath·of'),
    (7, 12, 'a·living'),
    (7, 13, 'soul'),
    (8, 3, 'a·garden·in·Eden'),
    (8, 4, 'in·the·east'),
    (8, 7, 'the·man'),
    (8, 9, 'formed'),
    (9, 0, 'and·caused·to·grow'),
    (9, 3, 'from·the·ground'),
    (9, 5, 'pleasing'),
    (9, 6, 'to·look·at'),
    (9, 7, 'and·good'),
    (9, 8, 'for·food'),
    (9, 10, 'the·life'),
    (9, 11, 'in·the·midst·of'),
    (9, 12, 'the·garden'),
    (9, 15, 'good'),
    (10, 0, 'and·a·river'),
    (10, 1, 'went·out'),
    (10, 2, 'from·Eden'),
    (10, 4, 'the·garden'),
    (10, 5, 'and·from·there'),
    (10, 7, 'and·became'),
    (10, 9, 'branches'),
    (11, 0, 'the·name·of'),
    (11, 4, 'winds·through'),
    (11, 5, '[identifies object]'),
    (11, 6, 'all·the·land·of'),
    (11, 8, 'the·gold'),
    (11, 9, 'the·gold'),
    (12, 2, 'that'),
    (12, 3, 'good'),
    (13, 0, 'and·the·name·of'),
    (13, 1, 'the·second'),
    (14, 0, 'and·the·name·of'),
    (14, 1, 'the·river'),
    (14, 5, 'flows'),
    (14, 6, 'east·of'),
    (14, 8, 'and·the·river'),
    (14, 9, 'the·fourth'),
    (14, 11, 'Euphrates'),
    (15, 3, 'the·man'),
    (15, 4, 'and·placed·him'),
    (15, 5, 'in·the·garden·of·Eden'),
    (15, 6, 'to·work·it'),
    (15, 7, 'and·to·keep·it'),
    (16, 0, 'and·commanded'),
    (16, 3, 'upon·the·man'),
    (16, 6, 'tree·of·the·garden'),
    (16, 7, 'freely'),
    (16, 8, 'you·may·eat'),
    (17, 0, 'but·of·the·tree·of'),
    (17, 2, 'good'),
    (17, 6, 'from·it'),
    (17, 8, 'on·the·day'),
    (17, 9, 'you·eat'),
    (17, 10, 'from·it'),
    (17, 11, 'surely'),
    (17, 12, 'you·shall·die'),
    (18, 3, 'not·good'),
    (18, 4, 'for·to·be'),
    (18, 6, 'alone'),
    (18, 7, 'I·will·make·for·him'),
    (18, 8, 'a·helper'),
    (18, 9, 'suitable·for·him'),
    (19, 0, 'and·formed'),
    (19, 3, 'from·the·ground'),
    (19, 4, 'every·beast·of'),
    (19, 9, 'and·brought'),
    (19, 10, 'to·the·man'),
    (19, 11, 'to·see'),
    (19, 12, 'what·he·would·call'),
    (19, 13, 'and·whatever'),
    (19, 15, 'called'),
    (19, 18, 'a·living'),
    (19, 19, 'creature'),
    (19, 21, 'its·name'),
    (20, 2, 'names'),
    (20, 3, 'to·all·the·livestock'),
    (20, 4, 'and·to·the·birds·of'),
    (20, 6, 'and·to·every'),
    (20, 7, 'beast·of'),
    (20, 9, 'but·for·the·man'),
    (20, 10, 'not·found'),
    (20, 11, 'a·helper'),
    (20, 12, 'suitable·for·him'),
    (21, 0, 'and·caused·to·fall'),
    (21, 4, 'upon·the·man'),
    (21, 8, 'his·ribs'),
    (21, 11, 'in·its·place'),
    (22, 3, 'the·rib'),
    (22, 4, 'which·he·took'),
    (22, 5, 'from·the·man'),
    (22, 6, 'into·a·woman'),
    (22, 7, 'and·brought·her'),
    (22, 8, 'to·the·man'),
    (23, 0, 'and·said'),
    (23, 1, 'the·man'),
    (24, 0, 'therefore'),
    (24, 1, 'shall·leave'),
    (24, 3, 'his·father'),
    (24, 4, 'and·his·mother'),
    (24, 5, 'and·cling'),
    (24, 6, 'to·his·wife'),
    (24, 7, 'and·they·shall·become'),
    (24, 8, 'one'),
    (24, 9, 'flesh'),
    (25, 0, 'and·they·were'),
    (25, 1, 'both·of·them'),
    (25, 2, 'naked'),
    (25, 3, 'the·man'),
    (25, 4, 'and·his·wife'),
    (25, 5, 'and·were·not'),
    (25, 6, 'ashamed'),
]

for verse_num, word_idx, correct in CH2:
    v = d['chapters'][1]['verses'][verse_num - 1]
    if word_idx < len(v['words']):
        v['words'][word_idx]['eng'] = correct

# Chapter 3 corrections
CH3 = [
    (1, 0, 'now·the·serpent'),
    (1, 1, 'was'),
    (1, 2, 'more·cunning'),
    (1, 3, 'than·any'),
    (1, 4, 'beast·of'),
    (1, 5, 'the·field'),
    (1, 7, 'and·he·said'),
    (1, 8, 'to·the·woman'),
    (1, 9, 'did·God·say'),
    (1, 10, 'not'),
    (1, 11, 'you·shall·eat'),
    (1, 12, 'from·any'),
    (1, 13, 'tree·of'),
    (1, 14, 'the·garden'),
    (2, 0, 'and·said'),
    (2, 1, 'the·woman'),
    (2, 2, 'to·the·serpent'),
    (2, 3, 'from·the·fruit·of'),
    (2, 4, 'the·trees·of'),
    (2, 5, 'the·garden'),
    (2, 6, 'we·may·eat'),
    (3, 0, 'but·from·the·fruit·of'),
    (3, 1, 'the·tree'),
    (3, 2, 'which·is·in·the·midst·of'),
    (3, 3, 'the·garden'),
    (3, 4, 'said'),
    (3, 5, 'God'),
    (3, 6, 'you·shall·not·eat'),
    (3, 7, 'from·it'),
    (3, 8, 'and·you·shall·not·touch'),
    (3, 9, 'it'),
    (3, 10, 'lest'),
    (3, 11, 'you·die'),
    (4, 0, 'and·said'),
    (4, 1, 'the·serpent'),
    (4, 2, 'to·the·woman'),
    (4, 3, 'not·die'),
    (4, 4, 'you·shall·die'),
    (5, 0, 'for'),
    (5, 1, 'knows'),
    (5, 2, 'God'),
    (5, 3, 'that·on·the·day'),
    (5, 4, 'you·eat'),
    (5, 5, 'from·it'),
    (5, 6, 'and·opened'),
    (5, 7, 'your·eyes'),
    (5, 8, 'and·you·shall·be'),
    (5, 9, 'like·God'),
    (5, 10, 'knowing'),
    (5, 11, 'good'),
    (5, 12, 'and·evil'),
    (6, 0, 'and·saw'),
    (6, 1, 'the·woman'),
    (6, 2, 'that·good'),
    (6, 3, 'the·tree'),
    (6, 4, 'for·food'),
    (6, 5, 'and·that·desirable'),
    (6, 6, 'it·was'),
    (6, 7, 'to·the·eyes'),
    (6, 8, 'and·pleasing'),
    (6, 9, 'the·tree'),
    (6, 10, 'to·make·wise'),
    (6, 11, 'and·she·took'),
    (6, 12, 'from·its·fruit'),
    (6, 13, 'and·ate'),
    (6, 14, 'and·she·gave'),
    (6, 15, 'also'),
    (6, 16, 'to·her·husband'),
    (6, 17, 'with·her'),
    (6, 18, 'and·he·ate'),
    (7, 0, 'and·were·opened'),
    (7, 1, 'the·eyes·of'),
    (7, 2, 'both·of·them'),
    (7, 3, 'and·they·knew'),
    (7, 4, 'that'),
    (7, 5, 'naked'),
    (7, 6, 'they·were'),
    (7, 7, 'and·they·sewed'),
    (7, 8, 'fig'),
    (7, 9, 'leaves'),
    (7, 10, 'and·made'),
    (7, 11, 'for·themselves'),
    (7, 12, 'coverings'),
    (8, 0, 'and·they·heard'),
    (8, 1, 'the·voice·of'),
    (8, 2, 'YHWH'),
    (8, 3, 'God'),
    (8, 4, 'walking'),
    (8, 5, 'in·the·garden'),
    (8, 6, 'in·the·breeze·of'),
    (8, 7, 'the·day'),
    (8, 8, 'and·hid'),
    (8, 9, 'the·man'),
    (8, 10, 'and·his·wife'),
    (8, 11, 'from·the·presence·of'),
    (8, 12, 'YHWH'),
    (8, 13, 'God'),
    (8, 14, 'among·the·trees·of'),
    (8, 15, 'the·garden'),
]

for verse_num, word_idx, correct in CH3:
    v = d['chapters'][2]['verses'][verse_num - 1]
    if word_idx < len(v['words']):
        v['words'][word_idx]['eng'] = correct

with open('K:/TorahByWord/genesis.json', 'w', encoding='utf-8') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)

print("Gen 2:1-8 after correction:")
for v in d['chapters'][1]['verses'][:8]:
    print(f'\n{v["ref"]}:  {v["translation"]}')
    for w in v['words']:
        print(f'  {w["heb"]:20s}  {w["eng"]}')
