#!/usr/bin/env python3
"""Hand-correct Genesis 5-10 verse by verse."""
import json, sys

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

with open('K:/TorahByWord/genesis.json', 'r', encoding='utf-8') as f:
    d = json.load(f)

def fix(ch_num, fixes):
    ch = d['chapters'][ch_num - 1]
    for verse_num, word_idx, correct in fixes:
        v = ch['verses'][verse_num - 1]
        if word_idx < len(v['words']):
            v['words'][word_idx]['eng'] = correct

# Chapter 5 — Genealogy of Adam
fix(5, [
    (1, 1, 'record·of'),
    (1, 2, 'the·generations·of'),
    (1, 3, 'Adam'),
    (1, 5, 'creating'),
    (1, 7, 'Adam'),
    (1, 8, 'in·the·likeness·of'),
    (1, 10, 'He·made'),
    (2, 2, 'He·created·them'),
    (2, 6, 'their·name'),
    (2, 7, 'Adam'),
    (2, 9, 'when·He·created·them'),
    (3, 1, 'Adam'),
    (3, 6, 'in·his·likeness'),
    (3, 7, 'after·his·image'),
    (5, 1, 'all·the·days·of'),
    (5, 2, 'Adam'),
    (6, 0, 'and·Seth·lived'),
    (7, 0, 'and·Seth·lived'),
    (8, 0, 'and·were'),
    (9, 1, 'Enosh'),
    (10, 1, 'Enosh'),
    (11, 2, 'Enosh'),
    (12, 0, 'and·lived'),
    (15, 0, 'and·lived'),
    (18, 0, 'and·lived'),
    (21, 0, 'and·lived'),
    (22, 0, 'and·Enoch·walked'),
    (24, 0, 'and·Enoch·walked'),
    (25, 0, 'and·lived'),
    (28, 0, 'and·lived'),
    (28, 1, 'Lamech'),
    (29, 0, 'and·he·called'),
    (29, 2, 'Noah'),
    (29, 3, 'saying'),
    (29, 4, 'this·one'),
    (29, 5, 'will·comfort·us'),
    (29, 6, 'from·our·work'),
    (29, 7, 'and·from·the·toil·of'),
    (29, 8, 'our·hands'),
    (29, 9, 'from·the·ground'),
    (29, 10, 'which'),
    (29, 11, 'cursed'),
    (30, 0, 'and·Lamech·lived'),
    (30, 2, 'begot'),
    (31, 1, 'all·the·days·of'),
    (31, 2, 'Lamech'),
    (32, 0, 'and·Noah·was'),
    (32, 3, 'years·old'),
    (32, 4, 'and·Noah·begot'),
    (32, 5, 'Shem'),
    (32, 6, 'Ham'),
    (32, 7, 'and·Japheth'),
])

# Chapter 6 — Corruption and Noah
fix(6, [
    (1, 0, 'and·it·was'),
    (1, 1, 'when'),
    (1, 2, 'began'),
    (1, 3, 'Adam'),
    (1, 4, 'to·multiply'),
    (1, 5, 'upon·the·face·of'),
    (1, 6, 'the·ground'),
    (1, 7, 'and·daughters'),
    (1, 8, 'were·born'),
    (1, 9, 'to·them'),
    (2, 0, 'and·saw'),
    (2, 1, 'the·sons·of'),
    (2, 2, 'God'),
    (2, 3, 'the·daughters·of'),
    (2, 4, 'man'),
    (2, 5, 'that'),
    (2, 6, 'beautiful'),
    (2, 7, 'they·were'),
    (2, 8, 'and·they·took'),
    (2, 9, 'for·themselves'),
    (2, 10, 'wives'),
    (2, 11, 'from·all'),
    (2, 12, 'whom'),
    (2, 13, 'they·chose'),
    (3, 0, 'and·said'),
    (3, 1, 'YHWH'),
    (3, 2, 'not'),
    (3, 3, 'shall·strive'),
    (3, 4, 'my·spirit'),
    (3, 5, 'in·man'),
    (3, 6, 'forever'),
    (3, 7, 'in·that·also'),
    (3, 8, 'he·is'),
    (3, 9, 'flesh'),
    (3, 10, 'and·his·days·shall·be'),
    (3, 11, 'a·hundred'),
    (3, 12, 'and·twenty'),
    (3, 13, 'years'),
    (4, 0, 'the·Nephilim'),
    (4, 1, 'were'),
    (4, 2, 'on·the·earth'),
    (4, 3, 'in·those·days'),
    (4, 4, 'and·also'),
    (4, 5, 'after'),
    (4, 6, 'that'),
    (4, 7, 'when'),
    (4, 8, 'came'),
    (4, 9, 'the·sons·of'),
    (4, 10, 'God'),
    (4, 11, 'to'),
    (4, 12, 'the·daughters·of'),
    (4, 13, 'man'),
    (4, 14, 'and·they·bore'),
    (4, 15, 'to·them'),
    (4, 16, 'those·were'),
    (4, 17, 'the·mighty·ones'),
    (4, 18, 'who·from'),
    (4, 19, 'old'),
    (4, 20, 'men·of'),
    (4, 21, 'renown'),
    (5, 0, 'and·YHWH·saw'),
    (5, 1, 'that'),
    (5, 2, 'great'),
    (5, 3, 'the·wickedness·of'),
    (5, 4, 'man'),
    (5, 5, 'on·the·earth'),
    (5, 6, 'and·every'),
    (5, 7, 'intention·of'),
    (5, 8, 'the·thoughts·of'),
    (5, 9, 'his·heart'),
    (5, 10, 'only'),
    (5, 11, 'evil'),
    (5, 12, 'all'),
    (5, 13, 'the·day'),
    (6, 0, 'and·YHWH·regretted'),
    (6, 1, 'that'),
    (6, 2, 'He·had·made'),
    (6, 3, 'man'),
    (6, 4, 'on·the·earth'),
    (6, 5, 'and·it·grieved'),
    (6, 6, 'Him'),
    (6, 7, 'to'),
    (6, 8, 'his·heart'),
    (7, 0, 'and·said'),
    (7, 1, 'YHWH'),
    (7, 2, 'I·will·blot·out'),
    (7, 3, 'man'),
    (7, 4, 'whom'),
    (7, 5, 'I·created'),
    (7, 6, 'from·the·face·of'),
    (7, 7, 'the·ground'),
    (7, 8, 'from·man'),
    (7, 9, 'to·beast'),
    (7, 10, 'to·creeping·thing'),
    (7, 11, 'and·to·birds·of'),
    (7, 12, 'the·heavens'),
    (7, 13, 'for'),
    (7, 14, 'I·regret'),
    (7, 15, 'that'),
    (7, 16, 'I·made·them'),
    (8, 0, 'but·Noah'),
    (8, 1, 'found'),
    (8, 2, 'favor'),
    (8, 3, 'in·the·eyes·of'),
    (8, 4, 'YHWH'),
    (9, 0, 'these·are'),
    (9, 1, 'the·generations·of'),
    (9, 2, 'Noah'),
    (9, 3, 'Noah'),
    (9, 4, 'was·a·righteous'),
    (9, 5, 'man'),
    (9, 6, 'blameless'),
    (9, 7, 'was·he'),
    (9, 8, 'in·his·generations'),
    (9, 9, 'with'),
    (9, 10, 'God'),
    (9, 11, 'walked'),
    (9, 12, 'Noah'),
    (10, 0, 'and·Noah·begot'),
    (10, 1, 'three'),
    (10, 2, 'sons'),
    (10, 3, 'Shem'),
    (10, 4, 'Ham'),
    (10, 5, 'and·Japheth'),
    (11, 0, 'and·the·earth·was·corrupt'),
    (11, 1, 'before'),
    (11, 2, 'God'),
    (11, 3, 'and·the·earth·was·filled'),
    (11, 4, 'with·violence'),
    (12, 0, 'and·God·saw'),
    (12, 1, 'the·earth'),
    (12, 2, 'and·behold'),
    (12, 3, 'it·was·corrupt'),
    (12, 4, 'for'),
    (12, 5, 'had·corrupted'),
    (12, 6, 'all'),
    (12, 7, 'flesh'),
    (12, 8, 'its·way'),
    (12, 9, 'upon·the·earth'),
    (13, 0, 'and·God·said'),
    (13, 1, 'to·Noah'),
    (13, 2, 'the·end·of'),
    (13, 3, 'all'),
    (13, 4, 'flesh'),
    (13, 5, 'has·come'),
    (13, 6, 'before·me'),
    (13, 7, 'for'),
    (13, 8, 'filled'),
    (13, 9, 'the·earth'),
    (13, 10, 'with·violence'),
    (13, 11, 'because·of·them'),
    (13, 12, 'and·behold'),
    (13, 13, 'I·will·destroy·them'),
    (13, 14, 'with·the·earth'),
    (14, 0, 'make'),
    (14, 1, 'for·yourself'),
    (14, 2, 'an·ark'),
    (14, 3, 'of·gopher·wood'),
    (14, 4, 'rooms'),
    (14, 5, 'you·shall·make'),
    (14, 6, 'the·ark'),
    (14, 7, 'and·cover·it'),
    (14, 8, 'inside'),
    (14, 9, 'and·outside'),
    (14, 10, 'with·pitch'),
])

with open('K:/TorahByWord/genesis.json', 'w', encoding='utf-8') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)

# Verify
print("Ch 5:1-3:")
for v in d['chapters'][4]['verses'][:3]:
    print(f'  {v["ref"]}:')
    for w in v['words']:
        print(f'    {w["heb"]:18s}  {w["eng"]}')

print("\nCh 6:1-4:")
for v in d['chapters'][5]['verses'][:4]:
    print(f'  {v["ref"]}:')
    for w in v['words']:
        print(f'    {w["heb"]:18s}  {w["eng"]}')
